"""Rig OS Vault Export - Obsidian-compatible Markdown vault projection.

Doctrine:
- Vault is a projection, not source of truth.
- Markdown is for human-operable memory.
- JSON/JSONL receipts remain machine evidence.
- SQLite is operational state.
- Projections are rebuildable read models.
- Vault export must be deterministic.
- Vault export must default to dry-run unless explicitly writing.
- Vault export must not mutate source docs.
- Vault export must not move/archive/delete files.
"""

from __future__ import annotations

import json
import os
import urllib.parse
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from rig_tools.state_store import StateStore
from rig_tools.settings_store import SettingsStore
from rig_tools.projections import ProjectionsBuilder


GENERATED_HEADER = "<!-- GENERATED BY RIG VAULT EXPORT. DO NOT EDIT THIS GENERATED NOTE DIRECTLY. SOURCE OF TRUTH IS RIG RECEIPTS/STATE. -->"


@dataclass
class VaultNote:
    """Represents a single vault note with frontmatter and body."""
    note_id: str
    rig_type: str
    title: str
    path: str
    frontmatter: Dict[str, Any]
    body_sections: List[str]
    links: List[str] = field(default_factory=list)
    source_artifacts: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    status: str = "pass"

    def to_markdown(self) -> str:
        """Render note as Markdown with YAML frontmatter."""
        lines = [GENERATED_HEADER, ""]
        lines.append("---")
        for key, value in self.frontmatter.items():
            if isinstance(value, list):
                if value:
                    lines.append(f"{key}:")
                    for item in value:
                        lines.append(f"  - {item}")
            elif isinstance(value, bool):
                lines.append(f"{key}: {str(value).lower()}")
            elif value is not None:
                lines.append(f"{key}: {value}")
            else:
                lines.append(f"{key}:")
        lines.append("---")
        lines.append("")
        lines.extend(self.body_sections)
        return "\n".join(lines)


@dataclass
class ExportManifest:
    """Represents a vault export manifest."""
    schema_version: str = "rig.vault_export.v1"
    export_id: str = ""
    created_at: str = ""
    status: str = "pass"
    vault_path: str = ""
    note_count: int = 0
    task_note_count: int = 0
    copied_json_count: int = 0
    copied_bundle_count: int = 0
    source_artifacts: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    notes: List[Dict[str, Any]] = field(default_factory=list)
    authoritative: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "export_id": self.export_id,
            "created_at": self.created_at,
            "status": self.status,
            "vault_path": self.vault_path,
            "note_count": self.note_count,
            "task_note_count": self.task_note_count,
            "copied_json_count": self.copied_json_count,
            "copied_bundle_count": self.copied_bundle_count,
            "source_artifacts": self.source_artifacts,
            "warnings": self.warnings,
            "notes": self.notes,
            "authoritative": self.authoritative,
        }


class VaultExporter:
    """Exports Rig state to an Obsidian-compatible vault."""

    VAULT_STRUCTURE = {
        "00 Dashboard.md": "dashboard",
        "01 Tasks": "tasks",
        "01 Tasks/index.md": "tasks_index",
        "02 Runs": "runs",
        "02 Runs/index.md": "runs_index",
        "03 Loops": "loops",
        "03 Loops/index.md": "loops_index",
        "04 Agents": "agents",
        "05 Models": "models",
        "06 Sentinels": "sentinels",
        "06 Sentinels/index.md": "sentinels_index",
        "07 GC": "gc",
        "07 GC/index.md": "gc_index",
        "08 Scheduler": "scheduler",
        "08 Scheduler/index.md": "scheduler_index",
        "09 Anigma": "anigma",
        "09 Anigma/index.md": "anigma_index",
        "10 Reference": "reference",
        "10 Reference/Settings.md": "settings_ref",
        "10 Reference/Actions.md": "actions_ref",
        "Attachments": "attachments",
        "Attachments/json": "attachments_json",
        "Attachments/bundles": "attachments_bundles",
    }

    REQUIRED_NOTES = [
        "00 Dashboard.md",
        "01 Tasks/index.md",
        "02 Runs/index.md",
        "03 Loops/index.md",
        "06 Sentinels/index.md",
        "07 GC/index.md",
        "08 Scheduler/index.md",
        "09 Anigma/index.md",
        "10 Reference/Settings.md",
        "10 Reference/Actions.md",
    ]

    def __init__(self, repo_root: Path, vault_path: Optional[Path] = None):
        self.repo_root = repo_root
        self.settings = SettingsStore(repo_root)
        self.state_store = StateStore(repo_root)
        self.projections = ProjectionsBuilder(repo_root)

        # Determine vault path
        if vault_path:
            self.vault_root = vault_path
        else:
            effective = self.settings.get_effective_settings()
            vault_path_str = effective.get("vault_path", ".build/rig/vault/Rig-vault")
            self.vault_root = self.repo_root / vault_path_str

        self.export_id = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        self.created_at = datetime.now(timezone.utc).isoformat()
        self.notes: List[VaultNote] = []
        self.warnings: List[str] = []
        self.copied_json_count = 0
        self.copied_bundle_count = 0
        self.source_artifacts: List[str] = []

    def get_status(self) -> Dict[str, Any]:
        """Returns the current status of the vault export subsystem."""
        return {
            "schema_version": "rig.vault_export.v1",
            "status": "pass",
            "vault_path": str(self.vault_root.relative_to(self.repo_root)),
            "export_count": 0,
            "latest_export_id": self.export_id,
            "warnings": self.warnings,
            "authoritative": False,
        }

    def build_dashboard_note(self) -> VaultNote:
        """Builds the 00 Dashboard.md note."""
        state_status = self.state_store.get_status()
        
        body = [
            "# Rig OS Dashboard",
            "",
            "Operational snapshot of Rig OS components.",
            "",
            "## Overview",
            "",
            "Rig OS is a repo-local development harness for Anigma. This dashboard",
            "provides a human-readable summary of the current system state.",
            "",
            "## State Store Status",
            f"",
            f"- **Status**: {state_status['status']}",
            f"- **DB Path**: `{state_status['db_path']}`",
            "",
            "## Quick Links",
            "",
            "- [[Task Graph]] - Task relationships and dependencies",
            "- [[Settings]] - Configuration reference",
            "- [[Actions]] - Available actions and commands",
            "- [[Anigma Sentinel]] - Architecture sentinel status",
            "- [[GC]] - Garbage collection plans and status",
            "",
            "## Subsystems",
            "",
            "- **Projections**: Task graph, Kanban board",
            "- **Loop Engine**: Agent loop policies and runs",
            "- **Scheduler**: Background job scheduling",
            "- **Garbage Collection**: Resource cleanup plans",
            "- **State Store**: Durable operational state in SQLite",
            "",
            "## Latest Activity",
            "",
            "See [[Task Graph]] for recent task updates.",
        ]

        frontmatter = {
            "rig_type": "dashboard",
            "title": "Rig OS Dashboard",
            "status": "pass",
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id="00-dashboard",
            rig_type="dashboard",
            title="Rig OS Dashboard",
            path="00 Dashboard.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Task Graph]]", "[[Settings]]", "[[Actions]]", "[[Anigma Sentinel]]", "[[GC]]"],
            source_artifacts=[state_status["db_path"]] if state_status["status"] != "missing" else [],
        )

    def build_tasks_index_note(self) -> VaultNote:
        """Builds the 01 Tasks/index.md note."""
        tasks = []
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM tasks").fetchall()
                tasks = [dict(r) for r in res]
        except Exception as e:
            self.warnings.append(f"Could not read tasks from state store: {e}")

        body = [
            "# Tasks",
            "",
            "Index of all tracked tasks from Rig state store.",
            "",
            "## Task Summary",
            f"",
            f"- **Total Tasks**: {len(tasks)}",
            "",
        ]

        if tasks:
            body.append("## Active Tasks")
            body.append("")
            for t in sorted(tasks, key=lambda x: x.get("task_id", "")):
                status = t.get("status", "unknown")
                label = t.get("label", t.get("task_id", "Unknown"))
                task_id = t.get("task_id", "")
                body.append(f"- [{status.upper()}] [[{task_id}|{label}]]")
            body.append("")
        else:
            body.append("No tasks found in state store.")
            body.append("")

        body.extend([
            "## Links",
            "",
            "- [[Task Graph]] - Task relationships",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "tasks_index",
            "title": "Tasks",
            "task_count": len(tasks),
            "status": "pass" if tasks else "warn",
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="01-tasks-index",
            rig_type="tasks_index",
            title="Tasks",
            path="01 Tasks/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Task Graph]]", "[[00 Dashboard]]"],
            source_artifacts=[".build/rig/state/rig.sqlite"] if self.state_store.db_path.exists() else [],
        )

        if not tasks:
            note.warnings.append("No tasks found in state store")
            note.status = "warn"

        return note

    def build_task_note(self, task: Dict[str, Any]) -> VaultNote:
        """Builds a single task note."""
        task_id = task.get("task_id", "")
        label = task.get("label", task_id)
        status = task.get("status", "unknown")
        data = task.get("data") or {}
        
        # Parse data field if it's a JSON string
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except json.JSONDecodeError:
                data = {}
        if not isinstance(data, dict):
            data = {}
        
        created = task.get("created_at", "")
        updated = task.get("updated_at", "")

        body = [
            f"# {label}",
            "",
            f"**Task ID**: `{task_id}`",
            f"**Status**: {status.upper()}",
            "",
            "## Summary",
            "",
            str(data.get("description", "No description available.")),
            "",
            "## Status",
            "",
            f"- Current: {status}",
            "",
            "## Recommended Next Action",
            "",
            "Check task status in state store and update accordingly.",
            "",
            "## Links",
            "",
            "- [[Task Graph]]",
            "- [[Tasks]]",
            "- [[00 Dashboard]]",
        ]

        frontmatter = {
            "rig_type": "task",
            "task_id": task_id,
            "title": label,
            "status": status,
            "risk": data.get("risk", "unknown"),
            "blocked_by": data.get("blocked_by", []),
            "blocks": data.get("blocks", []),
            "latest_run": data.get("latest_run", ""),
            "latest_loop": data.get("latest_loop", ""),
            "latest_bundle": data.get("latest_bundle", ""),
            "updated": updated,
            "authoritative": False,
        }

        return VaultNote(
            note_id=f"task-{task_id}",
            rig_type="task",
            title=label,
            path=f"01 Tasks/{task_id}.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Task Graph]]", "[[Tasks]]", "[[00 Dashboard]]"],
            source_artifacts=[str(self.state_store.db_path.relative_to(self.repo_root))],
        )

    def build_runs_index_note(self) -> VaultNote:
        """Builds the 02 Runs/index.md note."""
        runs = []
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM action_results ORDER BY finished_at DESC").fetchall()
                runs = [dict(r) for r in res]
        except Exception as e:
            self.warnings.append(f"Could not read action_results from state store: {e}")

        body = [
            "# Runs",
            "",
            "Index of action results and runs from Rig state store.",
            "",
            "## Summary",
            f"",
            f"- **Total Runs**: {len(runs)}",
            "",
        ]

        if runs:
            body.append("## Recent Runs")
            body.append("")
            for r in runs[:10]:
                result_id = r.get("result_id", "")
                action_id = r.get("action_id", "")
                status = r.get("status", "unknown")
                finished = r.get("finished_at", "")
                body.append(f"- [{status.upper()}] {action_id} - {finished}")
            body.append("")
        else:
            body.append("No runs found in state store.")
            body.append("")

        body.extend([
            "## Links",
            "",
            "- [[00 Dashboard]] - Main dashboard",
            "- [[Tasks]] - All tasks",
        ])

        frontmatter = {
            "rig_type": "runs_index",
            "title": "Runs",
            "run_count": len(runs),
            "status": "pass" if runs else "warn",
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="02-runs-index",
            rig_type="runs_index",
            title="Runs",
            path="02 Runs/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[00 Dashboard]]", "[[Tasks]]"],
            source_artifacts=[".build/rig/state/rig.sqlite"] if self.state_store.db_path.exists() else [],
        )

        if not runs:
            note.warnings.append("No runs found in state store")
            note.status = "warn"

        return note

    def build_loops_index_note(self) -> VaultNote:
        """Builds the 03 Loops/index.md note."""
        loop_runs = []
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM loop_runs ORDER BY created_at DESC").fetchall()
                loop_runs = [dict(r) for r in res]
        except Exception as e:
            self.warnings.append(f"Could not read loop_runs from state store: {e}")

        body = [
            "# Loops",
            "",
            "Index of loop runs from Rig state store.",
            "",
            "## Summary",
            f"",
            f"- **Total Loop Runs**: {len(loop_runs)}",
            "",
        ]

        if loop_runs:
            body.append("## Recent Loop Runs")
            body.append("")
            for lr in loop_runs[:10]:
                loop_run_id = lr.get("loop_run_id", "")
                task = lr.get("task", "")
                status = lr.get("status", "unknown")
                created = lr.get("created_at", "")
                body.append(f"- [{status.upper()}] {task} - {loop_run_id} - {created}")
            body.append("")
        else:
            body.append("No loop runs found in state store.")
            body.append("")

        body.extend([
            "## Links",
            "",
            "- [[00 Dashboard]] - Main dashboard",
            "- [[Tasks]] - All tasks",
            "- [[Loop Engine]] - Loop engine documentation",
        ])

        frontmatter = {
            "rig_type": "loops_index",
            "title": "Loops",
            "loop_run_count": len(loop_runs),
            "status": "pass" if loop_runs else "warn",
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="03-loops-index",
            rig_type="loops_index",
            title="Loops",
            path="03 Loops/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[00 Dashboard]]", "[[Tasks]]", "[[Loop Engine]]"],
            source_artifacts=[".build/rig/state/rig.sqlite"] if self.state_store.db_path.exists() else [],
        )

        if not loop_runs:
            note.warnings.append("No loop runs found in state store")
            note.status = "warn"

        return note

    def build_loop_note(self, loop_run: Dict[str, Any]) -> VaultNote:
        """Builds a single loop run note."""
        loop_run_id = loop_run.get("loop_run_id", "")
        task = loop_run.get("task", "")
        status = loop_run.get("status", "unknown")
        data = loop_run.get("data") or {}
        
        # Parse data field if it's a JSON string
        if isinstance(data, str):
            try:
                data = json.loads(data)
            except json.JSONDecodeError:
                data = {}
        if not isinstance(data, dict):
            data = {}
        
        created = loop_run.get("created_at", "")

        body = [
            f"# Loop Run: {loop_run_id}",
            "",
            f"**Task**: `{task}`",
            f"**Status**: {status.upper()}",
            f"**Created**: {created}",
            "",
            "## Summary",
            "",
            str(data.get("summary", "No summary available.")),
            "",
            "## Status",
            "",
            f"- Current: {status}",
            "",
            "## Stop Reason",
            "",
            str(data.get("stop_reason", "Not stopped yet.")),
            "",
            "## Artifacts",
            "",
        ]

        artifacts = data.get("artifacts", [])
        if isinstance(artifacts, list):
            for art in artifacts:
                body.append(f"- {art}")
        elif isinstance(artifacts, dict):
            for name, path in artifacts.items():
                body.append(f"- **{name}**: {path}")

        body.extend([
            "",
            "## Links",
            "",
            "- [[Loops]] - All loop runs",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "loop_run",
            "run_id": loop_run_id,
            "task": task,
            "status": status,
            "stop_reason": data.get("stop_reason", ""),
            "artifacts": artifacts,
            "created": created,
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id=f"loop-{loop_run_id}",
            rig_type="loop_run",
            title=f"Loop Run: {loop_run_id}",
            path=f"03 Loops/{loop_run_id}.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Loops]]", "[[00 Dashboard]]"],
            source_artifacts=[str(self.state_store.db_path.relative_to(self.repo_root))],
        )

    def build_sentinels_index_note(self) -> VaultNote:
        """Builds the 06 Sentinels/index.md note."""
        # Try to read latest sentinel results
        sentinel_path = self.repo_root / ".build" / "rig" / "os-sentinel" / "latest.json"
        sentinel_data = {}
        if sentinel_path.exists():
            try:
                sentinel_data = json.loads(sentinel_path.read_text(encoding="utf-8"))
            except Exception:
                pass

        status = sentinel_data.get("status", "unknown")
        subsystems = sentinel_data.get("subsystems", [])
        missing = sentinel_data.get("missing_required_subsystems", [])

        body = [
            "# Sentinels",
            "",
            "Rig OS and Anigma Architecture sentinel status.",
            "",
            "## Rig OS Sentinel",
            f"",
            f"- **Status**: {status.upper()}",
            f"- **Subsystems**: {len(subsystems)}",
            "",
        ]

        if subsystems:
            body.append("### Subsystem Status")
            body.append("")
            for sub in subsystems:
                sub_id = sub.get("subsystem_id", "")
                sub_status = sub.get("status", "unknown")
                marker = "X" if sub_status == "pass" else " "
                body.append(f"- [{marker}] **{sub_id.upper()}**: {sub_status.upper()}")
            body.append("")

        if missing:
            body.append("### Missing Required Subsystems")
            body.append("")
            for m in missing:
                body.append(f"- {m}")
            body.append("")

        body.extend([
            "## Anigma Architecture Sentinel",
            "",
            "Architecture sentinel monitors contract boundaries and tier violations.",
            "See [[Anigma Sentinel]] for details.",
            "",
            "## Links",
            "",
            "- [[Anigma Sentinel]] - Architecture sentinel",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "sentinels_index",
            "title": "Sentinels",
            "status": status,
            "missing_subsystems": missing,
            "subsystem_count": len(subsystems),
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="06-sentinels-index",
            rig_type="sentinels_index",
            title="Sentinels",
            path="06 Sentinels/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Anigma Sentinel]]", "[[00 Dashboard]]"],
            source_artifacts=[".build/rig/os-sentinel/latest.json"],
        )

        return note

    def build_anigma_sentinel_note(self) -> VaultNote:
        """Builds the Anigma Sentinel note."""
        # Try to read architecture sentinel results
        arch_sentinel_path = self.repo_root / "Docs" / "governance" / "anigma_architecture_sentinel.json"
        arch_data = {}
        if arch_sentinel_path.exists():
            try:
                arch_data = json.loads(arch_sentinel_path.read_text(encoding="utf-8"))
            except Exception:
                pass

        status = arch_data.get("status", "unknown")
        issues = arch_data.get("issues", [])

        body = [
            "# Anigma Sentinel",
            "",
            "Architecture Sentinel monitors contract boundaries, tier violations, and forbidden imports.",
            "",
            "## Current Status",
            f"",
            f"- **Status**: {status.upper()}",
            f"- **Issues**: {len(issues)}",
            "",
        ]

        if issues:
            body.append("## Issues")
            body.append("")
            for issue in issues[:20]:
                code = issue.get("code", "")
                severity = issue.get("severity", "unknown")
                message = issue.get("message", "")
                body.append(f"- [{severity.upper()}] **{code}**: {message}")
            body.append("")

        body.extend([
            "## Issue Families",
            "",
            "- Tier violations (Tier 1 -> Tier 2 -> Tier 3)",
            "- Forbidden @_exported imports",
            "- Dependency cycles",
            "- Contract drift",
            "",
            "## Links",
            "",
            "- [[Sentinels]] - All sentinels",
            "- [[00 Dashboard]] - Main dashboard",
            "- [[Latest Receipt|.build/rig/os-sentinel/latest.json]]",
        ])

        frontmatter = {
            "rig_type": "anigma_sentinel",
            "title": "Anigma Sentinel",
            "status": status,
            "issue_count": len(issues),
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id="anigma-sentinel",
            rig_type="anigma_sentinel",
            title="Anigma Sentinel",
            path="06 Sentinels/Anigma Sentinel.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Sentinels]]", "[[00 Dashboard]]", "[[Latest Receipt|.build/rig/os-sentinel/latest.json]]"],
            source_artifacts=[".build/rig/os-sentinel/latest.json"] if arch_sentinel_path.exists() else [],
        )

    def build_scheduler_index_note(self) -> VaultNote:
        """Builds the 08 Scheduler/index.md note."""
        scheduler_jobs = []
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM scheduler_jobs").fetchall()
                scheduler_jobs = [dict(r) for r in res]
        except Exception as e:
            self.warnings.append(f"Could not read scheduler_jobs from state store: {e}")

        body = [
            "# Scheduler",
            "",
            "Rig OS background job scheduling status.",
            "",
            "## Known Jobs",
            f"",
            f"- **Total Jobs**: {len(scheduler_jobs)}",
            "",
        ]

        if scheduler_jobs:
            body.append("## Job Status")
            body.append("")
            for job in scheduler_jobs:
                name = job.get("job_name", "")
                schedule = job.get("schedule", "")
                enabled = job.get("data", {})
                # Parse data for enabled status
                data = job.get("data") or {}
                try:
                    job_data = json.loads(data) if isinstance(data, str) else data
                    enabled = job_data.get("enabled", True)
                except Exception:
                    enabled = True
                status_str = "Enabled" if enabled else "Disabled"
                body.append(f"- [{status_str}] **{name}**: `{schedule}`")
            body.append("")
        else:
            body.append("No scheduler jobs found in state store.")
            body.append("")

        effective_settings = self.settings.get_effective_settings()
        scheduler_enabled = effective_settings.get("scheduler_enabled", False)

        body.extend([
            f"## Scheduler Status",
            "",
            f"- **Scheduler Enabled**: {scheduler_enabled}",
            "- **plist Paths**: macOS LaunchAgent plist files in ~/Library/LaunchAgents/",
            "- **Dry-run Mode**: Always safe by default; explicit --apply required for mutations",
            "",
            "## Links",
            "",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "scheduler_index",
            "title": "Scheduler",
            "job_count": len(scheduler_jobs),
            "scheduler_enabled": scheduler_enabled,
            "status": "pass" if scheduler_jobs else "warn",
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="08-scheduler-index",
            rig_type="scheduler_index",
            title="Scheduler",
            path="08 Scheduler/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[00 Dashboard]]"],
            source_artifacts=[".build/rig/state/rig.sqlite"] if self.state_store.db_path.exists() else [],
        )

        if not scheduler_jobs:
            note.warnings.append("No scheduler jobs found in state store")
            note.status = "warn"

        return note

    def build_gc_index_note(self) -> VaultNote:
        """Builds the 07 GC/index.md note."""
        gc_marks = []
        gc_runs = []
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM gc_marks").fetchall()
                gc_marks = [dict(r) for r in res]
                res = conn.execute("SELECT * FROM action_results WHERE action_id LIKE '%gc%'").fetchall()
                gc_runs = [dict(r) for r in res]
        except Exception as e:
            self.warnings.append(f"Could not read GC data from state store: {e}")

        # Try to read latest GC plan
        gc_plan_path = self.repo_root / ".build" / "rig" / "gc" / "latest-plan.json"
        plan_data = {}
        if gc_plan_path.exists():
            try:
                plan_data = json.loads(gc_plan_path.read_text(encoding="utf-8"))
            except Exception:
                pass

        bytes_reclaimable = plan_data.get("bytes_reclaimable", 0)
        delete_count = plan_data.get("delete_count", 0)
        protected = plan_data.get("protected", [])

        body = [
            "# Garbage Collection",
            "",
            "Rig OS garbage collection plans and status.",
            "",
            "## Latest GC Plan",
            f"",
            f"- **Plan ID**: {plan_data.get('plan_id', 'N/A')}",
            f"- **Delete Candidates**: {delete_count}",
            f"- **Protected Files**: {len(protected)}",
            f"- **Bytes Reclaimable**: {bytes_reclaimable}",
            "",
        ]

        if gc_marks:
            body.append("## Marked Paths")
            body.append("")
            classes = {}
            for mark in gc_marks:
                pclass = mark.get("class", "unknown")
                path = mark.get("path", "")
                classes.setdefault(pclass, []).append(path)
            for pclass, paths in sorted(classes.items()):
                body.append(f"### {pclass}")
                body.append("")
                for p in paths[:10]:
                    body.append(f"- {p}")
                if len(paths) > 10:
                    body.append(f"- ... and {len(paths) - 10} more")
                body.append("")

        body.extend([
            "## Docs Normalization",
            "",
            "Docs normalization plan manages document duplicates and archive candidates.",
            "",
            "- Archive Candidates Summary",
            "- Protected Count",
            "- Bytes Reclaimable",
            "",
            "## Links",
            "",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "gc_index",
            "title": "GC",
            "delete_candidates": delete_count,
            "protected_count": len(protected),
            "bytes_reclaimable": bytes_reclaimable,
            "marked_paths_count": len(gc_marks),
            "status": "pass" if delete_count > 0 else "warn",
            "updated": self.created_at,
            "authoritative": False,
        }

        note = VaultNote(
            note_id="07-gc-index",
            rig_type="gc_index",
            title="GC",
            path="07 GC/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[00 Dashboard]]"],
            source_artifacts=[".build/rig/gc/latest-plan.json"] if gc_plan_path.exists() else [],
        )

        if not plan_data:
            note.warnings.append("No GC plan found")
        if delete_count == 0:
            note.warnings.append("No delete candidates in latest plan")

        return note

    def build_anigma_index_note(self) -> VaultNote:
        """Builds the 09 Anigma/index.md note."""
        body = [
            "# Anigma",
            "",
            "Anigma adapter artifacts and integration status.",
            "",
            "## Architecture Sentinel Summary",
            "",
            "Monitors contract boundaries between Tier 1 (Contracts), Tier 2 (Substrate), and Tier 3 (Feature/Daemon).",
            "",
            "- Tier 1 must not import Tier 2 or Tier 3",
            "- Tier 2 must not import Tier 3",
            "- No dependency cycles",
            "- No shell=True in production code",
            "",
            "## Remediation Loop Summary",
            "",
            "Boundary remediation tracks and fixes tier violations and coupling issues.",
            "",
            "## Issue Families",
            "",
            "- Tier violations",
            "- Forbidden @_exported imports",
            "- Dependency cycles",
            "- Contract drift",
            "- Hot-path payload copies",
            "",
            "## Latest Receipt Paths",
            "",
            "- .build/rig/os-sentinel/latest.json",
            "- Docs/governance/anigma_architecture_sentinel.json",
            "",
            "## Links",
            "",
            "- [[Anigma Sentinel]] - Architecture sentinel details",
            "- [[00 Dashboard]] - Main dashboard",
            "- [[Rig OS Sentinel|06 Sentinels]] - OS sentinel status",
        ]

        frontmatter = {
            "rig_type": "anigma_index",
            "title": "Anigma",
            "status": "pass",
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id="09-anigma-index",
            rig_type="anigma_index",
            title="Anigma",
            path="09 Anigma/index.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Anigma Sentinel]]", "[[00 Dashboard]]", "[[Rig OS Sentinel|06 Sentinels]]"],
            source_artifacts=[".build/rig/os-sentinel/latest.json", "Docs/governance/anigma_architecture_sentinel.json"],
        )

    def build_settings_reference_note(self) -> VaultNote:
        """Builds the 10 Reference/Settings.md note."""
        effective = self.settings.get_effective_settings()
        paths = self.settings.get_paths()

        body = [
            "# Settings",
            "",
            "Rig OS configuration reference.",
            "",
            "## Configuration Layers",
            "",
            "Settings are merged from multiple layers with the following precedence:",
            "",
            "1. **User Settings**: ~/.config/rig/settings.toml",
            "2. **Project Settings**: .rig/settings.toml",
            "3. **Runtime Settings**: .build/rig/tui/settings.json",
            "4. **Environment Variables**: RIG_* prefix",
            "",
            f"## Current Effective Settings",
            "",
            f"```toml",
        ]

        # Add key settings
        for key in ["default_mode", "active_model_backend", "vault_path", "state_path", "projection_path"]:
            value = effective.get(key)
            if value is not None:
                body.append(f"{key} = {json.dumps(value)}")

        body.append("```")

        body.extend([
            "## Settings Commands",
            "",
            "- `rig settings show` - Show effective settings",
            "- `rig settings init` - Initialize project settings",
            "- `rig settings set <key> <value>` - Set a setting value",
            "- `rig settings paths` - Show settings file paths",
            "- `rig settings validate` - Validate settings against schema",
            "",
            "## Links",
            "",
            "- [[Actions]] - Available actions and commands",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "settings_reference",
            "title": "Settings",
            "settings_layer": "effective",
            "user_settings_path": paths.get("user", ""),
            "project_settings_path": paths.get("project", ""),
            "status": "pass",
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id="10-reference-settings",
            rig_type="settings_reference",
            title="Settings",
            path="10 Reference/Settings.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Actions]]", "[[00 Dashboard]]"],
            source_artifacts=[paths.get("user", ""), paths.get("project", "")],
        )

    def build_actions_reference_note(self) -> VaultNote:
        """Builds the 10 Reference/Actions.md note."""
        body = [
            "# Actions",
            "",
            "Rig OS action reference.",
            "",
            "## Action Registry",
            "",
            "Actions are typed operations that can be executed through the ActionRegistry.",
            "Each action has a unique action_id, label, and associated data.",
            "",
            "## Available Action Types",
            "",
            "- **atlas**: Build and query architecture atlas",
            "- **audit**: Run audit lanes (state-flow, zero-copy, contracts)",
            "- **brief**: Generate task briefs from templates",
            "- **bundle**: Create session review bundles",
            "- **db**: DuckDB analytical indexing",
            "- **docs**: Documentation indexing and tables",
            "- **doctor**: Health checks and diagnostics",
            "- **git**: Git operations with explicit plans",
            "- **llm**: Local LLM model operations",
            "- **loop**: Supervisor loop orchestration",
            "- **monitor**: System monitoring and snapshot",
            "- **notify**: Desktop notifications",
            "- **os sentinel**: Rig OS sentinel validation",
            "- **patch**: Local patch proposals",
            "- **pipeline**: Anigma pipeline execution",
            "- **policy**: Policy decision recording",
            "- **prompt**: Prompt lab operations",
            "- **queue**: Durable job queue",
            "- **scheduler**: Background job scheduling",
            "- **schema**: JSON schema validation",
            "- **settings**: Configuration management",
            "- **state**: State store operations",
            "- **swift**: Swift build/test diagnostics",
            "- **tui**: Textual TUI operations",
            "- **vault**: Vault export operations",
            "",
            "## Command Patterns",
            "",
            "All actions can be executed via:",
            "- `rig <group> <command> [options]`",
            "",
            "## Safety",
            "",
            "- **Safe Mode**: Read-only operations only",
            "- **Action Mode**: Guarded execution with manual approval",
            "- **Auto-Approve Mode**: Bounded autonomous execution with policy",
            "",
            "## Links",
            "",
            "- [[Settings]] - Configuration reference",
            "- [[00 Dashboard]] - Main dashboard",
        ]

        frontmatter = {
            "rig_type": "actions_reference",
            "title": "Actions",
            "action_count": 0,  # Will be updated when action registry is available
            "status": "pass",
            "updated": self.created_at,
            "authoritative": False,
        }

        return VaultNote(
            note_id="10-reference-actions",
            rig_type="actions_reference",
            title="Actions",
            path="10 Reference/Actions.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Settings]]", "[[00 Dashboard]]"],
            source_artifacts=[".build/rig/results/latest.json"],
        )

    def build_sentinel_note(self) -> VaultNote:
        """Builds Rig OS Sentinel note from latest sentinel receipt."""
        sentinel_path = self.repo_root / ".build" / "rig" / "os-sentinel" / "latest.json"
        if not sentinel_path.exists():
            return None

        try:
            sentinel_data = json.loads(sentinel_path.read_text(encoding="utf-8"))
        except Exception:
            return None

        status = sentinel_data.get("status", "unknown")
        subsystems = sentinel_data.get("subsystems", [])
        missing = sentinel_data.get("missing_required_subsystems", [])
        issues = sentinel_data.get("issues", [])

        body = [
            "# Rig OS Sentinel",
            "",
            f"Rig OS Sentinel validation results. Generated: {sentinel_data.get('created_at', 'N/A')}",
            "",
            "## Status",
            f"",
            f"- **Overall Status**: {status.upper()}",
            f"- **Exit Code**: {sentinel_data.get('exit_code', 0)}",
            "",
        ]

        body.append("## Subsystems")
        body.append("")
        for sub in subsystems:
            sub_id = sub.get("subsystem_id", "")
            sub_status = sub.get("status", "unknown")
            marker = "X" if sub_status == "pass" else " "
            body.append(f"- [{marker}] **{sub_id.upper()}**: {sub_status.upper()}")
        body.append("")

        if missing:
            body.append("## Missing Required Subsystems")
            body.append("")
            for m in missing:
                body.append(f"- {m}")
            body.append("")

        if issues:
            body.append("## Issues")
            body.append("")
            for issue in issues[:20]:
                code = issue.get("code", "")
                severity = issue.get("severity", "unknown")
                message = issue.get("message", "")
                body.append(f"- [{severity.upper()}] **{code}**: {message}")
            if len(issues) > 20:
                body.append(f"- ... and {len(issues) - 20} more")
            body.append("")

        body.extend([
            "## Latest Receipt Path",
            "",
            f"- {sentinel_path.relative_to(self.repo_root)}",
            "",
            "## Links",
            "",
            "- [[Sentinels]] - All sentinels",
            "- [[00 Dashboard]] - Main dashboard",
        ])

        frontmatter = {
            "rig_type": "sentinel",
            "title": "Rig OS Sentinel",
            "status": status,
            "subsystem_count": len(subsystems),
            "missing_count": len(missing),
            "issue_count": len(issues),
            "updated": sentinel_data.get("created_at", self.created_at),
            "authoritative": False,
        }

        return VaultNote(
            note_id="rig-os-sentinel",
            rig_type="sentinel",
            title="Rig OS Sentinel",
            path="06 Sentinels/Rig OS Sentinel.md",
            frontmatter=frontmatter,
            body_sections=body,
            links=["[[Sentinels]]", "[[00 Dashboard]]"],
            source_artifacts=[str(sentinel_path.relative_to(self.repo_root))],
        )

    def collect_all_notes(self, copy_json: bool = False, copy_bundles: bool = False) -> List[VaultNote]:
        """Collects all notes to be exported."""
        notes: List[VaultNote] = []

        # Always include required notes
        notes.append(self.build_dashboard_note())
        notes.append(self.build_tasks_index_note())
        notes.append(self.build_runs_index_note())
        notes.append(self.build_loops_index_note())
        notes.append(self.build_sentinels_index_note())
        notes.append(self.build_scheduler_index_note())
        notes.append(self.build_gc_index_note())
        notes.append(self.build_anigma_index_note())
        notes.append(self.build_anigma_sentinel_note())
        notes.append(self.build_settings_reference_note())
        notes.append(self.build_actions_reference_note())

        # Add sentinel note if receipt exists
        sentinel_note = self.build_sentinel_note()
        if sentinel_note:
            notes.append(sentinel_note)

        # Add task notes
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM tasks").fetchall()
                tasks = [dict(r) for r in res]
        except Exception:
            tasks = []

        for task in tasks:
            notes.append(self.build_task_note(task))

        # Add loop run notes
        try:
            with self.state_store.connect() as conn:
                res = conn.execute("SELECT * FROM loop_runs").fetchall()
                loop_runs = [dict(r) for r in res]
        except Exception:
            loop_runs = []

        for loop_run in loop_runs:
            notes.append(self.build_loop_note(loop_run))

        # Track source artifacts
        self.source_artifacts = list(set(self.source_artifacts + [
            ".build/rig/state/rig.sqlite",
            ".build/rig/os-sentinel/latest.json",
        ]))

        # Copy JSON receipts if requested
        if copy_json:
            self._copy_json_receipts()

        # Copy bundles if requested
        if copy_bundles:
            self._copy_bundles()

        return notes

    def _copy_json_receipts(self):
        """Copies selected JSON receipts to vault attachments."""
        attachments_json_dir = self.vault_root / "Attachments" / "json"
        attachments_json_dir.mkdir(parents=True, exist_ok=True)

        # Copy key receipts
        receipt_paths = [
            ".build/rig/os-sentinel/latest.json",
            ".build/rig/state/status.json" if (self.repo_root / ".build" / "rig" / "state" / "status.json").exists() else None,
            ".build/rig/projections/latest.json" if (self.repo_root / ".build" / "rig" / "projections" / "latest.json").exists() else None,
        ]

        for path_str in receipt_paths:
            if path_str:
                src = self.repo_root / path_str
                if src.exists():
                    dst = attachments_json_dir / src.name
                    dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
                    self.copied_json_count += 1
                    self.source_artifacts.append(path_str)

    def _copy_bundles(self):
        """Copies selected bundle manifests to vault attachments."""
        attachments_bundles_dir = self.vault_root / "Attachments" / "bundles"
        attachments_bundles_dir.mkdir(parents=True, exist_ok=True)

        # Copy session bundle manifests if they exist
        session_bundles_dir = self.repo_root / "Session-bundles"
        if session_bundles_dir.exists():
            for manifest in session_bundles_dir.glob("*.manifest.json"):
                dst = attachments_bundles_dir / manifest.name
                dst.write_text(manifest.read_text(encoding="utf-8"), encoding="utf-8")
                self.copied_bundle_count += 1
                self.source_artifacts.append(str(manifest.relative_to(self.repo_root)))

    def export(self, dry_run: bool = False, copy_json: bool = False, copy_bundles: bool = False) -> ExportManifest:
        """Exports all notes to the vault."""
        notes = self.collect_all_notes(copy_json=copy_json, copy_bundles=copy_bundles)

        manifest = ExportManifest(
            schema_version="rig.vault_export.v1",
            export_id=self.export_id,
            created_at=self.created_at,
            status="pass",
            vault_path=str(self.vault_root.relative_to(self.repo_root)),
            note_count=len(notes),
            task_note_count=sum(1 for n in notes if n.rig_type == "task"),
            copied_json_count=self.copied_json_count,
            copied_bundle_count=self.copied_bundle_count,
            source_artifacts=self.source_artifacts,
            warnings=self.warnings,
            authoritative=False,
        )

        if dry_run:
            # Write dry-run preview receipt only
            dry_run_dir = self.repo_root / ".build" / "rig" / "vault" / "dry-run"
            dry_run_dir.mkdir(parents=True, exist_ok=True)
            
            # Write manifest
            manifest_path = dry_run_dir / f"{self.export_id}.json"
            manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2), encoding="utf-8")

            # Write preview of each note (truncated)
            preview_dir = dry_run_dir / "preview"
            preview_dir.mkdir(exist_ok=True)
            for note in notes:
                preview_path = preview_dir / f"{note.note_id}.preview.md"
                content = note.to_markdown()
                if len(content) > 2000:
                    content = content[:2000] + "\n\n... (truncated)"
                preview_path.write_text(content, encoding="utf-8")

            manifest.status = "dry_run"
            manifest.vault_path = str(preview_dir.relative_to(self.repo_root))
            return manifest

        # Write actual vault notes
        self.vault_root.mkdir(parents=True, exist_ok=True)

        written_count = 0
        for note in notes:
            note_path = self.vault_root / note.path
            note_path.parent.mkdir(parents=True, exist_ok=True)
            note_path.write_text(note.to_markdown(), encoding="utf-8")
            written_count += 1

            # Add to manifest notes
            manifest.notes.append({
                "note_id": note.note_id,
                "rig_type": note.rig_type,
                "title": note.title,
                "path": note.path,
                "source_artifacts": note.source_artifacts,
                "links": note.links,
                "frontmatter": note.frontmatter,
                "status": note.status,
                "warnings": note.warnings,
            })

        # Write manifest
        manifest_path = self.vault_root / "rig-vault-export-manifest.json"
        manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2), encoding="utf-8")

        # Update status based on warnings
        if manifest.warnings:
            manifest.status = "warn"

        return manifest

    def get_obsidian_uri(self, note_path: str, vault_name: str = "Rig-vault") -> str:
        """Generates an Obsidian URI for a note."""
        # Percent-encode the file path including forward slashes
        encoded_path = urllib.parse.quote(note_path, safe='')
        return f"obsidian://open?vault={vault_name}&file={encoded_path}"
