"""Base Runtime Adapter for Rig.

This module provides the base class for all runtime adapters.

Core doctrine:
- Models propose; Rig governs.
- Adapters NEVER directly mutate authority state.
- All adapter outputs are proposals that must be validated.
- Adapters are replay-safe and deterministic where possible.

file: src/rig/domain/runtimes/base.py
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, FrozenSet, List, Optional, Protocol, runtime_checkable, Tuple, TYPE_CHECKING

if TYPE_CHECKING:
    from rig.domain.runtime import (
        RuntimeProvider,
        RuntimeInvocation,
        RuntimeProposal,
        RuntimeExecutionReceipt,
        RuntimeCapabilityKind,
    )

from rig.domain.runtime import (
    PLACEHOLDER_UNKNOWN,
    PLACEHOLDER_NO_PROVIDER,
    PLACEHOLDER_NO_RECEIPT,
    RuntimeProvider,
    RuntimeProviderKind,
    RuntimeProviderTrustTier,
    RuntimeProviderStatus,
    RuntimeCapabilityKind,
    RuntimeInvocation,
    RuntimeProposal,
    RuntimeExecutionReceipt,
)


# =============================================================================
# Adapter Result Types
# =============================================================================

@dataclass(frozen=True, slots=True)
class AdapterResult:
    """Result from a runtime adapter invocation.
    
    Attributes:
        invocation: The runtime invocation that was executed
        proposals: List of proposals generated by the adapter
        raw_output: Raw output from the adapter
        execution_receipt: Receipt for the execution
        success: Whether the adapter execution succeeded
        error_message: Error message if failed
    """
    invocation: RuntimeInvocation
    proposals: List[RuntimeProposal] = field(default_factory=list)
    raw_output: str = ""
    execution_receipt: Optional[RuntimeExecutionReceipt] = None
    success: bool = True
    error_message: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "invocation": self.invocation.to_dict(),
            "proposals": [p.to_dict() for p in self.proposals],
            "raw_output": self.raw_output,
            "execution_receipt": self.execution_receipt.to_dict() if self.execution_receipt else None,
            "success": self.success,
            "error_message": self.error_message,
        }


# =============================================================================
# Adapter Configuration
# =============================================================================

@dataclass(frozen=True, slots=True)
class AdapterConfig:
    """Configuration for a runtime adapter."""
    adapter_id: str = PLACEHOLDER_UNKNOWN
    provider_id: str = PLACEHOLDER_NO_PROVIDER
    model_id: str = PLACEHOLDER_UNKNOWN
    timeout_seconds: float = 300.0
    max_tokens: Optional[int] = None
    temperature: float = 0.0  # Deterministic by default
    supported_capabilities: FrozenSet[RuntimeCapabilityKind] = field(default_factory=frozenset)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "adapter_id": self.adapter_id,
            "provider_id": self.provider_id,
            "model_id": self.model_id,
            "timeout_seconds": self.timeout_seconds,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
            "supported_capabilities": [k.value for k in self.supported_capabilities],
        }


# =============================================================================
# Adapter Capability Declaration
# =============================================================================

@dataclass(frozen=True, slots=True)
class AdapterCapabilities:
    """Declare the capabilities supported by an adapter."""
    adapter_id: str
    supported_capability_kinds: FrozenSet[RuntimeCapabilityKind]
    default_capability_kinds: FrozenSet[RuntimeCapabilityKind] = field(default_factory=frozenset)
    
    @classmethod
    def generate_proposal_capabilities(cls) -> "AdapterCapabilities":
        """Create capabilities for a proposal-only adapter."""
        return cls(
            adapter_id="proposal-only",
            supported_capability_kinds=frozenset([
                RuntimeCapabilityKind.FILE_READ,
                RuntimeCapabilityKind.FILE_WRITE_PROPOSAL,
                RuntimeCapabilityKind.SHELL_PROPOSAL,
                RuntimeCapabilityKind.PATCH_PROPOSAL,
                RuntimeCapabilityKind.REPLAY_ACCESS,
                RuntimeCapabilityKind.NETWORK_FETCH_PROPOSAL,
                RuntimeCapabilityKind.DOCS_FETCH_PROPOSAL,
                RuntimeCapabilityKind.TELEMETRY_EXPORT_PROPOSAL,
            ]),
            default_capability_kinds=frozenset([
                RuntimeCapabilityKind.FILE_READ,
                RuntimeCapabilityKind.REPLAY_ACCESS,
            ]),
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "adapter_id": self.adapter_id,
            "supported_capability_kinds": [k.value for k in self.supported_capability_kinds],
            "default_capability_kinds": [k.value for k in self.default_capability_kinds],
        }


# =============================================================================
# Base Runtime Adapter
# =============================================================================

class BaseRuntimeAdapter(ABC):
    """Abstract base class for runtime adapters.
    
    All runtime adapters must:
    - Implement invoke() method
    - Be deterministic where possible
    - Not mutate authority state
    - Produce proposals, not execute directly
    - Generate receipts for all invocations
    - Be replay-safe
    
    Properties:
    - No real API keys required
    - No production networking (in stubs)
    - No hidden execution
    - No background daemons
    """
    
    def __init__(
        self,
        adapter_id: str,
        provider_id: str = PLACEHOLDER_NO_PROVIDER,
        model_id: str = PLACEHOLDER_UNKNOWN,
        config: Optional[AdapterConfig] = None,
    ):
        self.adapter_id = adapter_id
        self.provider_id = provider_id
        self.model_id = model_id
        self.config = config or AdapterConfig(
            adapter_id=adapter_id,
            provider_id=provider_id,
            model_id=model_id,
        )
        self._capabilities = self.declare_capabilities()
    
    @property
    def capabilities(self) -> AdapterCapabilities:
        """Get the adapter's capabilities."""
        return self._capabilities
    
    @abstractmethod
    def declare_capabilities(self) -> AdapterCapabilities:
        """Declare the capabilities supported by this adapter."""
        ...
    
    @abstractmethod
    def get_provider(self) -> RuntimeProvider:
        """Get the runtime provider for this adapter."""
        ...
    
    @abstractmethod
    def invoke(
        self,
        request: Dict[str, Any],
        workspace_id: Optional[str] = None,
        actor_id: Optional[str] = None,
        capability_kinds: Optional[FrozenSet[RuntimeCapabilityKind]] = None,
    ) -> AdapterResult:
        """Invoke the adapter with a request.
        
        This method MUST:
        - Not mutate authority state
        - Return proposals, not execute directly
        - Generate receipts
        - Be deterministic where possible
        
        args:
            request: The invocation request
            workspace_id: Optional workspace context
            actor_id: Optional actor context
            capability_kinds: Optional set of capability kinds to use
        
        Returns:
            AdapterResult with invocation, proposals, and receipt
        """
        ...
    
    def create_invocation(
        self,
        request: Dict[str, Any],
        workspace_id: Optional[str] = None,
        actor_id: Optional[str] = None,
    ) -> RuntimeInvocation:
        """Create a runtime invocation for this adapter."""
        return RuntimeInvocation.create(
            provider_id=self.provider_id,
            model_id=self.model_id,
            request=request,
            workspace_id=workspace_id,
            actor_id=actor_id,
        )
    
    def create_execution_receipt(
        self,
        invocation: RuntimeInvocation,
        proposals: List[RuntimeProposal],
        duration_seconds: Optional[float] = None,
        token_metadata: Optional[Dict[str, int]] = None,
    ) -> RuntimeExecutionReceipt:
        """Create an execution receipt for this adapter."""
        from rig.domain.runtime import RuntimeProviderTrustTier
        
        provider = self.get_provider()
        
        return RuntimeExecutionReceipt.from_invocation(
            invocation=invocation,
            duration_seconds=duration_seconds,
            proposal_ids=frozenset(p.proposal_id for p in proposals),
            token_metadata=token_metadata,
        )
    
    def get_trust_tier(self) -> RuntimeProviderTrustTier:
        """Get the trust tier for this adapter's provider."""
        provider = self.get_provider()
        return provider.trust_tier
    
    def get_default_capabilities(self) -> FrozenSet[RuntimeCapabilityKind]:
        """Get the default capability kinds for this adapter."""
        return self._capabilities.default_capability_kinds
    
    def supports_capability(self, kind: RuntimeCapabilityKind) -> bool:
        """Check if this adapter supports a capability kind."""
        return kind in self._capabilities.supported_capability_kinds
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "adapter_id": self.adapter_id,
            "provider_id": self.provider_id,
            "model_id": self.model_id,
            "config": self.config.to_dict(),
            "capabilities": self.capabilities.to_dict(),
            "provider": self.get_provider().to_dict(),
        }
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(adapter_id={self.adapter_id}, provider_id={self.provider_id}, model_id={self.model_id})"
