"""
Domain modules for Rig.

These modules provide the core domain logic and serve as the deep modules
behind the CLI command adapters. Each domain module exposes a narrow,
well-defined interface that hides implementation complexity.

The interface is the test surface.
"""

from rig.domain.workspace import WorkspaceDomain, WorkspaceRecord, WORKSPACE_STATUSES
from rig.domain.runtime_events import (
    RuntimeEvent,
    RuntimeLifecycleEvent,
    RuntimeTelemetryEvent,
    ReplayEvent,
    TopologyDeltaEvent,
    GovernanceStateEvent,
    ExecutionRoutingEvent,
    WorkspaceLifecycleEvent,
    IntegrationStatusEvent,
)
from rig.domain.runtime_event_router import RuntimeEventRouter
from rig.domain.runtime_event_transport import RuntimeEventEnvelope, envelope_from_event, event_from_envelope
from rig.domain.workspace_runtime import WorkspaceRuntime
from rig.domain.execution_telemetry import ExecutionTelemetrySample, normalize_telemetry
from rig.domain.replay_event_bridge import ReplayTimelineEntry, ReplayEventBridgeResult, build_replay_timeline
from rig.domain.reconciliation_governance import (
    ReconciliationCadence,
    DampingFactor,
    RetryCeiling,
    ConvergenceWindow,
    CancellationPolicy,
    EventStormConfig,
    ConvergenceInfo,
    DampingInfo,
    RetryInfo,
    LoopHealthState,
    ReconciliationContext,
    AuthorityBoundaryViolationError,
    check_authority_violation,
    enforce_authority_boundary,
)
from rig.domain.runtime_reconciliation import (
    LoopStatus as RuntimeReconciliationLoopStatus,
    ControllerType,
    ReconciliationController,
    RuntimeSupervisionController,
    ProjectionRefreshController,
    TelemetryAggregationController,
    WorkspaceHygieneController as RuntimeWorkspaceHygieneController,
    TopologyDensityController,
)
from rig.domain.projection_reconciliation import (
    ProjectionRefreshPriority,
    ProjectionRefreshTrigger,
    ProjectionRefreshConfig,
    ProjectionState,
    ProjectionRefreshStats,
    ProjectionInvalidationReason,
    ProjectionInvalidation,
    ProjectionRefreshScheduler,
    ProjectionRebuildTrigger,
    ProjectionReconciliationController as ProjectionReconciliationController,
)
from rig.domain.telemetry_reconciliation import (
    TelemetryLoopType,
    TelemetryMetricType,
    TelemetryMetricConfig,
    TelemetryAggregationConfig,
    TelemetrySample,
    AggregatedMetric,
    TelemetryAggregationLoop,
    ThroughputStabilizationLoop,
    QueueDepthConvergenceLoop,
    RuntimeCoolingLoop,
    CadenceStabilizationLoop,
    DensityConvergenceLoop,
    TelemetryReconciliationController,
)
from rig.domain.workspace_hygiene import (
    WorkspaceHygieneAction,
    WorkspaceHygieneStatus,
    ArtifactCategory,
    ArtifactInfo,
    NamespaceInfo,
    RuntimeHealthInfo,
    IsolationInfo,
    HygieneAction,
    WorkspaceHygieneStats,
    WorkspaceHygieneConfig,
    WorkspaceHygieneController as WorkspaceHygieneLoopController,
    WorkspaceHygieneLoop,
)

__all__ = [
    "WorkspaceDomain",
    "WorkspaceRecord",
    "WORKSPACE_STATUSES",
    "RuntimeEvent",
    "RuntimeLifecycleEvent",
    "RuntimeTelemetryEvent",
    "ReplayEvent",
    "TopologyDeltaEvent",
    "GovernanceStateEvent",
    "ExecutionRoutingEvent",
    "WorkspaceLifecycleEvent",
    "IntegrationStatusEvent",
    "RuntimeEventRouter",
    "RuntimeEventEnvelope",
    "envelope_from_event",
    "event_from_envelope",
    "WorkspaceRuntime",
    "ExecutionTelemetrySample",
    "normalize_telemetry",
    "ReplayTimelineEntry",
    "ReplayEventBridgeResult",
    "build_replay_timeline",
    "ReconciliationCadence",
    "DampingFactor",
    "RetryCeiling",
    "ConvergenceWindow",
    "CancellationPolicy",
    "EventStormConfig",
    "ConvergenceInfo",
    "DampingInfo",
    "RetryInfo",
    "LoopHealthState",
    "ReconciliationContext",
    "AuthorityBoundaryViolationError",
    "check_authority_violation",
    "enforce_authority_boundary",
    "RuntimeReconciliationLoopStatus",
    "ControllerType",
    "ReconciliationController",
    "RuntimeSupervisionController",
    "ProjectionRefreshController",
    "TelemetryAggregationController",
    "RuntimeWorkspaceHygieneController",
    "TopologyDensityController",
    "ProjectionRefreshPriority",
    "ProjectionRefreshTrigger",
    "ProjectionRefreshConfig",
    "ProjectionState",
    "ProjectionRefreshStats",
    "ProjectionInvalidationReason",
    "ProjectionInvalidation",
    "ProjectionRefreshScheduler",
    "ProjectionRebuildTrigger",
    "ProjectionReconciliationController",
    "TelemetryLoopType",
    "TelemetryMetricType",
    "TelemetryMetricConfig",
    "TelemetryAggregationConfig",
    "TelemetrySample",
    "AggregatedMetric",
    "TelemetryAggregationLoop",
    "ThroughputStabilizationLoop",
    "QueueDepthConvergenceLoop",
    "RuntimeCoolingLoop",
    "CadenceStabilizationLoop",
    "DensityConvergenceLoop",
    "TelemetryReconciliationController",
    "WorkspaceHygieneAction",
    "WorkspaceHygieneStatus",
    "ArtifactCategory",
    "ArtifactInfo",
    "NamespaceInfo",
    "RuntimeHealthInfo",
    "IsolationInfo",
    "HygieneAction",
    "WorkspaceHygieneStats",
    "WorkspaceHygieneConfig",
    "WorkspaceHygieneLoopController",
    "WorkspaceHygieneLoop",
]
